openapi: 3.0.0
info:
  title: Greeter
  version: 0.0.1
paths:
  "/user/{name}":
    get:
      description: "Send a greeting using the name parameter"
      responses:
        200:
          description: "A succesful greeting has been sent"
          content:
            application/json:
              schema:
                type: string
    post:
      description: "Send a greeting using the name parameter"
      responses:
        200:
          description: "A succesful greeting has been sent"
          content:
            application/json:
              schema:
                type: string
    patch:
      description: "Send a greeting using the name parameter"
      responses:
        200:
          description: "A succesful greeting has been sent"
          content:
            application/json:
              schema:
                type: string
    delete:
      description: "Send a greeting using the name parameter"
      responses:
        200:
          description: "A succesful greeting has been sent"
          content:
            application/json:
              schema:
                type: string
    parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
  "/project/{id}":
    get:
      description: "Send a greeting using the name parameter"
      responses:
        200:
          description: "A succesful greeting has been sent"
          content:
            application/json:
              schema:
                type: string
    post:
      description: "Send a greeting using the name parameter"
      responses:
        200:
          description: "A succesful greeting has been sent"
          content:
            application/json:
              schema:
                type: string
    patch:
      description: "Send a greeting using the name parameter"
      responses:
        200:
          description: "A succesful greeting has been sent"
          content:
            application/json:
              schema:
                type: string
    delete:
      description: "Send a greeting using the name parameter"
      responses:
        200:
          description: "A succesful greeting has been sent"
          content:
            application/json:
              schema:
                type: string
    parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string